version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-qn7x
    environment:
      MYSQL_ROOT_PASSWORD: ht8ZG8tIsXTMrlOO6xU5DlxPmCC2xWhZNyNxWYOkFFo=
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"

  app:
    image: minielec7077/cafe:0.0.1
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysql
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ht8ZG8tIsXTMrlOO6xU5DlxPmCC2xWhZNyNxWYOkFFo=
    depends_on:
      - mysql
    ports:
      - "8080:8080"
