version: '3'
services:
  app:
    image: minielec7077/cafe:0.0.1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-qn7x:3306/mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=CLQgoNyxb6yLjPiKgN2k7swPAQAkZz3TJZ/SMhajEXg=
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"  # 변경된 포트를 여기서 명시합니다.
